project:
  type: website
  output-dir: _site

website:
  title: "Meera Chaddha"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Labs"
        file: labs.qmd
      - text: "About"
        file: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
