[project]
name = "meerachaddha-github-io"
version = "0.1.0"
description = ""
authors = [
    {name = "Meera Chaddha",email = "meerchad@bu.edu"}
]
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "meerachaddha"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
